version: '3.8'

services:
  web:
    image: mckayc/elosimplecomparison:dev
    container_name: elocompare
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: elocompare
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: unless-stopped
