version: '3.8'

services:
  web:
    image: mckayc/elosimplecomparison:dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=mysql://username:password@db:3306/db_name
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=db_name
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
    volumes:
      - ./data/mysql:/var/lib/mysql
