version: '3.8'

services:
  web:
    image: mckayc/elosimplecomparison:dev
    container_name: elosimplecomparison_dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development