version: '3'
services:
  webapp:
    image: mckayc/elosimplecomparison:dev
    container_name: elocompare
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    image: sqlite:latest
    container_name: elocompare-db
    restart: unless-stopped
    volumes:
      - ./app/database.db:/app/database.db
