version: '3'
services:
  webapp:
    image: mckayc/elosimplecomparison:dev
    container_name: elocompare
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
