version: '3.8'

services:
  web:
    image: mckayc/elosimplecomparison:dev
    container_name: elocompare
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: elocompare/app.py
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: elocompare_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: elocompare
      MYSQL_USER: elocompareuser
      MYSQL_PASSWORD: elocomparepass
    volumes:
      - db_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  db_data:
