CREATE TABLE comparisons (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    item1 VARCHAR(255) NOT NULL,
    item2 VARCHAR(255) NOT NULL,
    winner VARCHAR(255) NOT NULL
);

CREATE TABLE items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    elo_rating INT DEFAULT 1200
);
